### ISSUE TITLE
Parse.com is not accepting new sign ups

### ISSUE THREAD

**Issue by madHamish42** [azat-co/fullstack-javascript#7]
Parse is not accepting new signups as it's shutting down it's service in January 28, 2017.
http://blog.parse.com/announcements/moving-on/

**Comment by azat-co** [comment]
@madHamish42 yes. I updated code and the text to use local parse server. you can deploy it to any free or paid cloud service such as AWS, Azure, etc.

```
npm i -g parse-server mongodb-runner
mongodb-runner start
parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://localhost/test
```
